### PR TITLE
Adding_attribute_Encryption : supporting encryption attribute

### PR DESCRIPTION
**Pull request by amf9t2**
Thanks to all contributors who worked on this. This is really helpful.

I am planning to use this in project but I can't get encryption attribute set because chef-freetds doesn't support this. (http://www.freetds.org/userguide/freetdsconf.htm)

I have updated default template to read encryption attribute. Could you please review and let me know if these changes are enough ?

Awaiting for your reply.

Thanks in advance.

### CODE REVIEW

**Comment by ouranos** [comment]
Looks good to me. Thanks for your contribution. I'll merge tomorrow and tag a new release.

**Comment by amf9t2** [comment]
Thanks for your quick response.

Awaiting for new release. 👍

**Comment by amf9t2** [comment]
Quick question in package.rb file, it is only checking 'debian' platform but I am using on 'rhel' platform. 

I would really appreciate if you can guide me to fix this. 

Thanks.

**Comment by amf9t2** [comment]
never mind..I am passing package install as source which fixed it. 

Any estimation when can I get this release ?

Thanks for your time and patience.

**Comment by amf9t2** [comment]
Hi, any update on releasing this ?

**Comment by ouranos** [comment]
Sorry about the delay,  was in holiday :sunglasses:.
I'm fixing the travis build and i'll pick your changes, I'll merge manually since you're changing the `CHANGELOG` and metadata.rb`.
It's easier if you keep these changes in a separate commit next time :wink:

**Comment by ouranos** [comment]
> Quick question in package.rb file, it is only checking 'debian' platform but I am using on 'rhel' platform.
> I would really appreciate if you can guide me to fix this.

The [package resource](https://docs.chef.io/resource_package.html) supports yum as well as apt that's used in Debian/Ubuntu.
So if you'd like to add support for rhel package, you just need to find the package name.
If it's the same you can add `'redhat'` to the condition,  if it's different just add an extra `case` and specify the package name.

**Comment by ouranos** [comment]
Released and pushed 0.3.0 to supermarket

**Pull request merged**
