### PR TITLE
Compile 0.95 from source

### PR DESCRIPTION
**Pull request by l8nite**
This also fixes a small bug with the freetds conf location when the parent dir doesn't exist

### CODE REVIEW

**Comment by ouranos** [comment]
Hi,

Thanks for your contribution.

Does this work for you? It seems that the mirror I'm using (http://mirrors.ibiblio.org/freetds/stable/) doesn't have the new version.
I think you need to update the `freetds_url` in the `recipes/source.rb` to point to the official ftp.

**Comment by l8nite** [comment]
Ah sorry I did that but forgot to push it up on that commit.  Will do as soon as I'm back at a computer. 

- Shaun

**Comment by l8nite** [comment]
This should be good to go now

**Comment by ouranos** [comment]
Sorry about the delay!

**Pull request merged**
